apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: console 
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: ${IMAGE_REPOSITORY}/console
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: console 
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/console.yaml

